new_user: true

greeting_type:
  default: 'Hello World!'
  type: enum
  choices:
   - 'Hello World!'
   - 'Hey!'
   - 'What''s up!'
   - 'Hi!'
   - 'Hello there!'
  description: 'Select a greeting type!'